// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlWcd4LKtInCLwiGPZ20htu0v-6NNZW00',
    appId: '1:179980408263:web:d2f1ca52e9be680ae775e2',
    messagingSenderId: '179980408263',
    projectId: 'login-c38a6',
    authDomain: 'login-c38a6.firebaseapp.com',
    storageBucket: 'login-c38a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWpMmCzRPkW8zb5f8tdUc8GVSPMDN3ThQ',
    appId: '1:179980408263:android:6079c3f7ed2eb857e775e2',
    messagingSenderId: '179980408263',
    projectId: 'login-c38a6',
    storageBucket: 'login-c38a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjnPDSvpT-gar7nSsw4qrFEhu-4KutMEE',
    appId: '1:179980408263:ios:a8431de6fff31bc6e775e2',
    messagingSenderId: '179980408263',
    projectId: 'login-c38a6',
    storageBucket: 'login-c38a6.firebasestorage.app',
    iosClientId: '179980408263-r3u5oere9c46dvqk6ceb510ibm1uk8m9.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjnPDSvpT-gar7nSsw4qrFEhu-4KutMEE',
    appId: '1:179980408263:ios:a8431de6fff31bc6e775e2',
    messagingSenderId: '179980408263',
    projectId: 'login-c38a6',
    storageBucket: 'login-c38a6.firebasestorage.app',
    iosClientId: '179980408263-r3u5oere9c46dvqk6ceb510ibm1uk8m9.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlWcd4LKtInCLwiGPZ20htu0v-6NNZW00',
    appId: '1:179980408263:web:ec1e9c81ba8cb539e775e2',
    messagingSenderId: '179980408263',
    projectId: 'login-c38a6',
    authDomain: 'login-c38a6.firebaseapp.com',
    storageBucket: 'login-c38a6.firebasestorage.app',
  );
}
